### ISSUE TITLE
Missing require file in SLDSC_default.zip

### ISSUE THREAD

**Issue by 1667857557** [ArtemKimUSC/CTFM#1] opened 2024-06-29 12:20 UTC
Dear Author,

We encountered an issue while running the provided workflow: it appears that the required directories, Whole_v4 and Whole, are missing. Could you please provide the related files?

Best regards,
Yu-Feng Huang

```
*********************************************************************
* LD Score Regression (LDSC)
* Version 1.0.1
* (C) 2014-2019 Brendan Bulik-Sullivan and Hilary Finucane
* Broad Institute of MIT and Harvard / MIT Department of Mathematics
* GNU General Public License v3
*********************************************************************
Call:
./ldsc.py \
--h2-cts sumstats_ready/M_TCSC.sumstats.gz \
--ref-ld-chr scripts/../data/1000G_EUR_Phase3/baselineLD_v2.3/baselineLD. \
--out out/SLDSC/GBM_TCSC//M_TCSC.2 \
--ref-ld-chr-cts out/SLDSC/GBM_TCSC//M_TCSC.2.cts \
--w-ld-chr scripts/../data/1000G_EUR_Phase3/weights/weights.hm3_noMHC.

Beginning analysis at Sat Jun 29 19:11:47 2024
Reading summary statistics from sumstats_ready/M_TCSC.sumstats.gz ...
Read summary statistics for 6801168 SNPs.
Reading reference panel LD Score from scripts/../data/1000G_EUR_Phase3/baselineLD_v2.3/baselineLD.[1-22] ... (ldscore_fromlist)
Read reference panel LD Scores for 1190321 SNPs.
Removing partitioned LD Scores with zero variance.
Reading regression weight LD Score from scripts/../data/1000G_EUR_Phase3/weights/weights.hm3_noMHC.[1-22] ... (ldscore_fromlist)
Read regression weight LD Scores for 1187349 SNPs.
After merging with reference panel LD, 1144894 SNPs remain.
After merging with regression SNP LD, 1142150 SNPs remain.
Removed 54 SNPs with chi^2 > 80 (1142096 SNPs remain)
Reading cts reference panel LD Score from scripts/../data/SLDSC/ENCFF186BOY_blood_bodily_fluid_T_cell/ENCFF186BOY_blood_bodily_fluid_T_cell.,scripts/../data/SLDSC/Whole_v4/whole.[1-22] ... (ldscore_fromlist)
Traceback (most recent call last):
  File "/root/bin/ldsc/ldsc.py", line 646, in <module>
    sumstats.cell_type_specific(args, log)
  File "/root/bin/ldsc/ldscore/sumstats.py", line 288, in cell_type_specific
    'cts reference panel LD Score', ps.ldscore_fromlist)
  File "/root/bin/ldsc/ldscore/sumstats.py", line 152, in _read_chr_split_files
    out = parsefunc(_splitp(chr_arg), _N_CHR, **kwargs)
  File "/root/bin/ldsc/ldscore/parse.py", line 103, in ldscore_fromlist
    y = ldscore(fh, num)
  File "/root/bin/ldsc/ldscore/parse.py", line 147, in ldscore
    first_fh = sub_chr(fh, chrs[0]) + suffix
IndexError: list index out of range

Analysis finished at Sat Jun 29 19:13:05 2024
Total time elapsed: 1.0m:17.88s
```

**Comment by ArtemKimUSC** [comment] 2024-07-01 17:15
Hi Yu-Feng, 

One of our users previously encountered the same issue which was caused by some problems in the S-LDSC annotation archives containing the data that CT-FM uses (the ones that you download with `bash install/download_reference.sh`).

I believe the problem was fixed with a small update two weeks ago, when did you download the archive?

**Comment by 1667857557** [comment] 2024-07-02 03:29
We re-ran the script and downloaded the related file by running bash install/download_reference.sh. However, it reported the same issue. Could you give me any further suggestions?

**Comment by 1667857557** [comment] 2024-07-02 08:55
We re-downloaded the dataset, and the problem has been solved!

**Closed as completed** 2024-07-02 08:55 UTC

**Comment by 1667857557** [comment] 2024-07-03 01:14
Hi Artem,
I have another question. In step 4, the command `bash scripts/4_CTFMSNP_default_annots.sh $SNP_LIST.bed $OUTPUT_DIRECTORY` requires a $SNP_LIST.bed input. We downloaded the BED file you provided, but should I input bedlist.txt or each BED file individually from the folder? it reports errors when we input the bedlist.txt
````
huang@TNR:/mnt/g/linux/CTFM$ bash scripts/4_CTFMSNP_default_annots.sh /mnt/g/linux/CTFM/bedlist.txt /mnt/g/linux/CTFM/out/
Mapping annotations for SNP:  ...
ABC_astrocyte-ENCODE.bed
Error: unable to open file or unable to determine types for file /mnt/g/linux/CTFM/out//tmp..bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
ABC_B_cell-ENCODE.bed
Error: unable to open file or unable to determine types for file /mnt/g/linux/CTFM/out//tmp..bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
ABC_bipolar_neuron_from_iPSC-ENCODE.bed
Error: unable to open file or unable to determine types for file /mnt/g/linux/CTFM/out//tmp..bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
ABC_cardiac_muscle_cell-ENCODE.bed
Error: unable to open file or unable to determine types for file /mnt/g/linux/CTFM/out//tmp..bed

- Please ensure that your file is TAB delimited (e.g., cat -t FILE).
- Also ensure that your file has integer chromosome coordinates in the
  expected columns (e.g., cols 2 and 3 for BED).
ABC_CD14-positive_monocyte-ENCODE.bed
Error: unable to open file or unable to determine types for file /mnt/g/linux/CTFM/out//tmp..bed
````

**Comment by ArtemKimUSC** [comment] 2024-07-03 21:01
Hi Yu-Feng, 

I slightly updated the documentation concerning the CT-FM-SNP as it was a little misleading. 
`$SNP_LIST.bed` should be a bed file coming from your analysis: it is a list of candidate SNPs for your GWAS (for example fine-mapped SNPs but it can also be a list of SNPs that you manually defined as candidates). The list needs to have hg19 coordinates and have the format as in the example below :

`chr1	100818727	100818728	rs17420882`
